sudo: false
language: ruby
cache: bundler
dist: precise

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export TZ=America/New_York
before_script:
  - cp config/database.yml.example config/database.yml
  - cp config/shards.yml.example config/shards.yml
  - cp config/faye.yml.example config/faye.yml
  - cp dotenv.example .env
  - mysql -e 'create database test_sparc_request;'
  - mysql -e 'create database cwf_test;'
  - cd ..
  - git clone https://github.com/sparc-request/sparc-request.git
  - cd sparc-request
  - rvm use $(< .ruby-version) --install --binary --fuzzy
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
  - cp config/database.yml.example config/database.yml
  - cp config/application.yml.example config/application.yml
  - cp config/epic.yml.example config/epic.yml
  - cp config/ldap.yml.example config/ldap.yml
  - RAILS_ENV=test bundle exec rake db:migrate
  - cd ../sparc-fulfillment
  - pwd
  - mkdir -p public/system/documents
  - rvm use $(< .ruby-version) --install --binary --fuzzy
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - RAILS_ENV=test bundle exec rake db:migrate
  - RAILS_ENV=test bundle exec rake assets:precompile
jobs:
  include:
    - script:
      - bundle exec rspec spec/api
      - bundle exec rspec spec/controllers
      - bundle exec rspec spec/helpers
      - bundle exec rspec spec/jobs
      - bundle exec rspec spec/lib
      - bundle exec rspec spec/models
      - bundle exec rspec spec/requests
    - script:
      - bundle exec rspec spec/features
